import { Outfit } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header/Header";
import { Footer } from "@/components/footer/Footer";
import Image from "next/image";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "NFTICO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head><meta name="yandex-verification" content="d6b4c98955dd18ec" /></head>
      <body className={outfit.className}>
        <Header className="header"/>
        <main className="main">
          {children}
        </main>
        <Footer className="footer"/>
      </body>
    </html>
  );
}
